table Orders
	lineageTag: 5361bdf7-378d-410a-8f9c-44e6b49803f8

	column orderid
		dataType: string
		lineageTag: 53751586-2208-4620-afe5-ee63c9c25b62
		summarizeBy: none
		sourceColumn: orderid

		annotation SummarizationSetBy = Automatic

	column salesdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c6e3135-90f2-492d-bcc0-86deec6f082b
		summarizeBy: none
		sourceColumn: salesdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column productid
		dataType: string
		lineageTag: 74c7f5c7-b592-48b3-a408-4fc8e1aa8027
		summarizeBy: none
		sourceColumn: productid

		annotation SummarizationSetBy = Automatic

	column customerid
		dataType: string
		lineageTag: cf010708-1b8f-45fc-abc1-983c5831c117
		summarizeBy: none
		sourceColumn: customerid

		annotation SummarizationSetBy = Automatic

	column personnelid
		dataType: string
		lineageTag: d2e284a9-fa60-4c89-8490-fac1a247691e
		summarizeBy: none
		sourceColumn: personnelid

		annotation SummarizationSetBy = Automatic

	column saleschannel
		dataType: string
		lineageTag: 2149cbf5-8286-4d9a-8c34-31a986d636ba
		summarizeBy: none
		sourceColumn: saleschannel

		annotation SummarizationSetBy = Automatic

	column paymentmode
		dataType: string
		lineageTag: 3fba5c28-501d-4526-a939-2a9b1015663a
		summarizeBy: none
		sourceColumn: paymentmode

		annotation SummarizationSetBy = Automatic

	column storeid
		dataType: string
		lineageTag: 8b1fa480-288c-462e-915d-a4ce550f4217
		summarizeBy: none
		sourceColumn: storeid

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: c9061130-5985-41dd-a0d9-8999451ef6dd
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column salesamount
		dataType: double
		lineageTag: c87a6a4c-9372-41c7-a5c0-f428d29cc649
		summarizeBy: sum
		sourceColumn: salesamount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(PostgreSQL.Database("127.0.0.1", "StyleScape_db"), "SELECT *#(lf)FROM orders#(lf)WHERE salesdate >= (SELECT MAX(salesdate) FROM orders) - INTERVAL '2 weeks'#(lf)AND salesdate <= (SELECT MAX(salesdate) FROM orders)", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"orderid", type text}, {"salesdate", type date}, {"productid", type text}, {"customerid", type text}, {"personnelid", type text}, {"storeid", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

